steps:
  #Execute SonarCloud Scan
  - name: maven:3-jdk-11
    entrypoint: mvn
    args: ['verify', 'sonar:sonar','-Dsonar.host.url=https://sonarcloud.io','-Dsonar.organization=gcpsourcecodereposcan','-Dsonar.projectKey=gcpvulnerableprojectkey','-Dsonar.login=${_SONAR_TOKEN}']